name: get matrix
on: workflow_dispatch

jobs:
  build:
    name: GetVersions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: ETCD_COMMIT
            repo: etcd-io/etcd
          - name: NODE_FEATURE_DISCOVERY_COMMIT
            repo: kubernetes-sigs/node-feature-discovery
    steps:
      - uses: actions/checkout@v3
      - run: |
          name=${{ matrix.include.name }}
          repo=${{ matrix.include.repo }}
          version1=$(curl -L https://api.github.com/repos/$repo/releases/latest | jq '.name' | tr -d '"')
          version2=$(grep "$name" base-tag.mk | cut -d'=' -f2)
          echo $name
          echo $repo
          echo $version1
          echo $version2
          echo "| $name | https://www.github.com/$repo | $version2 | $version1 |"

