name: get matrix
on: workflow_dispatch

jobs:
  get-matrix:
    name: GetMetrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - { n: ETCD_COMMIT,   r: etcd-io/etcd }
          - { n: NODE_FEATURE_DISCOVERY_COMMIT, r: kubernetes-sigs/node-feature-discovery }
    steps:
      - uses: actions/checkout@v3
      - run: |
          name=${{ matrix.component.n }}
          repo=${{ matrix.component.r }}
          version1=$(curl -L https://api.github.com/repos/$repo}/releases/latest | jq '.name' | tr -d '"')
          version2=$(grep "$name" base-tag.mk | cut -d'=' -f2)
          echo "| $name | https://www.github.com/$repo | $version2 | $version1 |" >> data-$name.md
      - uses: actions/upload-artifact@v4
        with:
          name: processed-data-${{ matrix.component.n }}
          path: data-${{ matrix.component.n }}.md
  upload:
    name: Upload
    needs: get-matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: processed-data-*
          merge-multiple: true
      - run: |
          echo \| name \| repo \| current version \| upstream version  \| > all.md
          echo \| --- \| --- \| --- \| --- \| >> all.md
          cat ./*.md >> all.md
      - uses: actions/upload-artifact@v4
        with:
          name: all
          path: all.md
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: processed-data-*
