name: get matrix
on: workflow_dispatch

jobs:
  get-matrix:
    name: GetMetrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: [[ETCD_COMMIT, etcd-io/etcd], [NODE_FEATURE_DISCOVERY_COMMIT, kubernetes-sigs/node-feature-discovery]]
    steps:
      - uses: actions/checkout@v3
      - run: |
          name=${{ matrix.include[0] }}
          repo=${{ matrix.include[1] }}
          #version1=$(curl -L https://api.github.com/repos/$repo/releases/latest | jq '.name' | tr -d '"')
          #version2=$(grep "$name" base-tag.mk | cut -d'=' -f2)
          echo "Name: $name"
          echo "Repository: $repo"
          #echo $version1
          #echo $version2

