name: get matrix
on: workflow_dispatch

jobs:
  get-matrix:
    name: GetMetrix
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        component:
          - { n: ETCD_COMMIT,   r: etcd-io/etcd }
          - { n: NODE_FEATURE_DISCOVERY_COMMIT, r: kubernetes-sigs/node-feature-discovery }
    steps:
      - uses: actions/checkout@v3
      - run: |
          name=${{ matrix.component.n }}
          repo=${{ matrix.component.r }}
          version1=$(curl -L https://api.github.com/repos/$repo/releases/latest | jq '.name' | tr -d '"')
          version2=$(grep "$name" base-tag.mk | cut -d'=' -f2)
          echo "| $name | https://www.github.com/$repo | $version2 | $version1 |" >> versions.md
  upload:
     uses: actions/upload-artifact@v4
       with:
         name: versions
         path: versions.md
