name: Example Workflow
on: workflow_dispatch

jobs:
  # Job 1 with Matrix
  generate-data:
    name: Generate Data
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dd: [1, 2, 3]  # Example data to process
    steps:
      - run: |
          d=${{ matrix.dd }}
          echo hello >> data.txt
  
  # Job 2 to process data
  process-results:
    name: Process Results
    runs-on: ubuntu-latest
    needs: generate-data
    steps:
      - run: |
          cat data.txt
          # Process all data in the file
