name: Example Workflow

on: workflow_dispatch

jobs:
  # Job 1 with Matrix
  generate-data:
    name: Generate Data
    runs-on: ubuntu-latest
    strategy:
      matrix:
        data: [1, 2, 3]  # Example data to process
    steps:
      - run: echo ${{ matrix.data }} >> output.txt
        # Simulate processing and saving data to a file
      - uses: actions/upload-artifact@v3
        with:
          name: processed-data-${{ matrix.data }}
          path: output-${{ matrix.data }}.txt

  # Job 2 to process data
  process-results:
    name: Process Results
    runs-on: ubuntu-latest
    needs: generate-data
    steps:
      - uses: actions/download-artifact@v3
        with:
          pattern: processed-data-*
      - run: |
          ls -R
