name: Example Workflow
on: workflow_dispatch

jobs:
  # Job 1 with Matrix
  generate-data:
    name: Generate Data
    runs-on: ubuntu-latest
    strategy:
      matrix:
        data: [1, 2, 3]  # Example data to process
    steps:
      - run: echo ${{ matrix.data }} >>  output-${{ matrix.data }}.txt
        # Simulate processing and saving data to a file
      - uses: actions/upload-artifact@v4
        with:
          name: processed-data-${{ matrix.data }}
          path: output-${{ matrix.data }}.txt

  # Job 2 to process data
  process-results:
    name: Process Results
    runs-on: ubuntu-latest
    needs: generate-data
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: processed-data-*
          merge-multiple: true
      - run: |
          cat ./*.txt > all.txt
      - uses: actions/upload-artifact@v4
        with:
          name: all
          path: all.txt
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: processed-data-*
      
