name: get versions
on: [push, repository_dispatch]

jobs:
  build:
    name: GetVersions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: etcd
        run: |
          version1=$(curl -L  https://api.github.com/repos/etcd-io/etcd/releases/latest | jq '.name' | tr -d '"')
          version2=$(grep ETCD_COMMIT base-tag.mk | cut -d'=' -f2)
          echo $version1 $version2
    
