name: get versions
on: workflow_dispatch

jobs:
  build:
    name: GetVersions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo \| name / repo \| current version \| upstream version  \| > versions.md
          echo \| ------- \|:------:\| -----:\| >> version.md
      - run: |
          name=ETCD_COMMIT
          repo=etcd-io/etcd
          version1=$(curl -L  https://api.github.com/$repo/releases/latest | jq '.name' | tr -d '"')
          version2=$(grep $name base-tag.mk | cut -d'=' -f2)
          echo \|$name https://api.github.com/$repo \| $version2 \|$version1 \| >> versions.md
      - run: |
          name=NODE_FEATURE_DISCOVERY_COMMIT
          repo=kubernetes-sigs/node-feature-discovery
          version1=$(curl -L  https://api.github.com/$repo/releases/latest | jq '.name' | tr -d '"')
          version2=$(grep $name base-tag.mk | cut -d'=' -f2)
          echo \|$name https://api.github.com/$repo \| $version2 \|$version1 \| >> versions.md
                 
      - uses: actions/upload-artifact@v4
        with:
          name: versions
          path: versions.md
    
