name: get versions
on: [push, repository_dispatch]

jobs:
  build:
    name: GetVersions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: etcd-version-2
        run: |
          version=$(curl -L  https://api.github.com/repos/etcd-io/etcd/releases/latest | jq '.name' | tr -d '"')
          echo "::set-output name=version::$version"" 
      - id: get-etcd-version
        run: |
          version=$(grep ETCD_COMMIT base-tag.mk | cut -d'=' -f2)
          echo "::set-output name=version::$version"" 
      - id: print-out
        run: |
          echo ${{ steps.etcd-version-2.output.version }}
          echo ${{ steps.get-etcd-version.output.version }}
    
